### ISSUE TITLE
Upgrade to POI 3.11

### ISSUE THREAD

**Issue by adrianblynch** [cfsimplicity/lucee-spreadsheet#1]
Is there a reason for using POI 3.7 over the newer 3.11?

Just curious.

**Comment by cfsimplicity** [comment]
Hi Adrian.

This is a direct adaptation of the cfteamadvance extension, just rewritten to work as a standalone library. I've used the same jars/versions because I know they work with code.

Definitely interested in upgrading, but not until I've got a test suite in place (the old extension didn't have one).

**Comment by adrianblynch** [comment]
Cool!

Will be interesting to see the way tests could be tackled with Excel file generation.

I'll be keeping an eye on this repo.

**Comment by cfsimplicity** [comment]
Indeed! I'm fairly new to testing but I guess an automated suite won't achieve much coverage. Probably needs manual tests to generate spreadsheets which are then eyeballed.

**Comment by cfsimplicity** [comment]
0.1.0 upgrades POI to 3.11 and includes a test suite.
