### ISSUE TITLE
includeQueryColumnNames in addRows() produces invalid xlsx

### ISSUE THREAD

**Issue by MordantWastrel** [cfsimplicity/lucee-spreadsheet#160]
OpenJDK 8u181, Alpine Linux in Docker, Lucee 5.3.2.38-SNAPSHOT, lucee-spreadsheet 2.0.2.

We have a working xlsx file generated from:

`spreadsheet.addRows(workbook = sheet, data = dataQuery );`

If we change it to:

`spreadsheet.addRows(workbook = sheet, data = dataQuery, includeQueryColumnNames = true );`

The file is generated but Excel (2019) complains: "We found a problem with some content in abc.xlsx. Do you want us to try and recover as much as we can?" And if you click yes, it recovers just the query header row and none of the data.

**Comment by cfsimplicity** [comment]
There does seem to be something odd going on with the `includeQueryColumnNames` option and the way some software reads the generated file.

The tests for it all pass. These check the data contained in the _unsaved_ workbook object with what's expected using that option i.e. the query column names included as a row in the data.

I've also tested writing to a file and then reading it back into a query with the library, again with the expected results,

But when I open the written file with Open Office, the query column row is missing! There's no warning of any kind though.

If I upload the file to Google Sheets however, the query column row is there! 

If I download the Google Sheet and open it in Open Office, the query column row is now there!

I'm afraid I don't have access to MS Excel so can't test that. They've withdrawn the free Excel Viewer which I used to use.

It would seem there's something not right with the file written to disk, but what the issue is and why it only seems to be a problem for some software I have no idea at the moment, sorry.

**Comment by marcelvanlangen** [comment]
We're having the same issue. As soon as we use includeQueryColumnNames =true, the error shows. The solution we've taken is to set it to false, and add the filenames as the first row to the dataQuery struct. A workaround until the problems with includeQueryColumnNames are solved.

**Comment by cfsimplicity** [comment]
@marcelvanlangen Which software are you using to open the spreadsheet file when you get the error? Excel also? Have you tried opening it with Google Sheets?

**Comment by marcelvanlangen** [comment]
I'm using Microsoft Office 365 ProPlus version 1808. I'm not sure if I can open it in Google Sheets, I'll let you know if I can open the resulting file in Google Sheets, I can look at that tomorrow!

**Comment by cfsimplicity** [comment]
Also, try reading the file back into a query:
```
result = spreadsheet.read( src="myGenerated.xlsx", format="query" );
WriteDump( result );
```
Does it error? If not, are the column names there?

**Comment by marcelvanlangen** [comment]
Step 1: I've created a spreadsheet using includeQueryColumnNames =true. Problem opening in MS Office. Next I've opened it in Google Sheets. Not a problem at all! Next I've read the spreadsheet and dumped the result, based on your example. There was not an error, but the column names were gone. They were replaced with column1, column2 etc. Hope this helps!

**Comment by cfsimplicity** [comment]
Thanks Marcel. Although I still don't understand why this is happening with XLSX files, I think I've found a fix, which I've just added it to the [develop branch](https://github.com/cfsimplicity/lucee-spreadsheet/tree/develop). Could you please test it with your data?

**Comment by marcelvanlangen** [comment]
You've already created a possible fix!? I'll make some room in the planning to test this this morning. Thanks in advance!

**Comment by cfsimplicity** [comment]
It seems to have resolved the problems I was seeing (mentioned above), but I don't have MS Excel to test with so need you to confirm when you get a chance. Thanks.

**Comment by marcelvanlangen** [comment]
You are a hero! It works! Many thanks for your quick solution. We'll pick it up when it shows up in the Master branch!
