### ISSUE TITLE
Allow rows generated from queries to ignore the query column data types

### ISSUE THREAD

**Issue by cfsimplicity** [cfsimplicity/lucee-spreadsheet#199]
Currently if you use `addRows()` or one of the convenience methods (e.g. `downloadFileFromQuery()`) to generate rows from a query, the cell data type will be set according to the column types in the query (e.g. VarChar, Date etc), rather than the individual cell values.

In most cases this will be fine, but VarChar columns may contain values that are not strings and which may not display properly when typed as `string`s.

Add an option in each of the relevant methods to ignore the query column types when populating rows and set the type according to the cell value, which is how population methods taking non-query data work (e.g. `addRow()`, `addColumn()`).

**Comment by cfsimplicity** [comment]
Solution: add an optional `ignoreQueryColumnDataTypes` argument to the following methods:
```
addRows()
binaryFromQuery()
downloadFileFromQuery()
workbookFromQuery()
writeFileFromQuery()
```

**Comment by JamoCA** [comment]
Using `ignoreQueryColumnDataTypes` may result in data loss.  I wrote a QuerytoCSV UDF and added a similar feature so that I could pass instructions as to how data should be outputted.  Some values are incorrectly detected and cast and it was better IMHO to intentionally cast them so it wouldn't result in any data loss.

__Example:__ A 16 digit varchar string is converted to scientific notation.  (I don't pass CCs, but "4444333322221111" is displayed in Excel as "4.44433E+15" and the underlying data is rounded to "4444333322221110".)  Passing "3.14159265359" returns a rounded 3.141592654, but retains the correct data.  I'm sure there's other examples.

__DATE/TIME AS TEXT EXAMPLE:__ I have client that hosts an annual event and requires millisecond accuracy.  Is there a way to output a varchar column with date/time values like "2017-06-23 18:39:49.206" and and not have Excel strip the accuracy?  (This is one of the primary reasons that we've been using CSV.)  I was previously using a 3rdparty command-line converter and would only have to escape with quotes for the value to be "displayed as text" and retain the accuracy.

**Comment by cfsimplicity** [comment]
I think this due to [Excel's limits](https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3), which include a max 15 digit precision for numbers.

This and other quirks will apply whenever you add values that aren't in a query object - which is currently the only way of controlling the types ahead of time (by manipulating the query's Column Types).

As I say, ACF does give you the [option of specifying](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-s/spreadsheetaddrow.html) which of Excel's limited data types you want to use when adding values. I guess that would give greater flexibility in the end so I should probably just knuckle down and try and implement that instead of this.

On date/time accuracy, I think [I answered that before](https://github.com/cfsimplicity/lucee-spreadsheet/issues/184)?

**Comment by cfsimplicity** [comment]
Although... being able to specify column types wouldn't solve your original problem, which was to have some values in a column as numbers and others in the same column as strings. Not sure how you could do that without writing your own pre- or post-logic.

Unless the number of likely "quirks" is small enough to write workarounds for them (e.g. if( number.Len() GT 15 ) cellType = "string" )?

What do you think?

**Comment by JamoCA** [comment]
Yes, You did answer date/time question before... which is why I wouldn't want that to be blindly converted from VARCHAR to Date or Time.

What are your thoughts on a "data type override"?

On a QueryToCSV UDF that I wrote, I pass an optional struct containing column names and the date type that should be used.  Since I'm outputting a text file, it's not as strict as the POI library where you may need to test the value first and fallback if failed.  For example, if `{"score"="numeric"}`, but one of the VARCHAR scores is not numeric, you'd need to fallback to `string` (instead of `blank` or throw an error).

The benefit is that querydata like this `['1','1','1','-','0','0','0']` (all as VARCHARs) are outputted as "numeric when possible", then you can select the Excel column of data and count `3` and average `0.5`.  If the column consists of "number stored as text", you can't perform any mathematical functions.

I believe that this optional level of granularity would enable developers to identify potentially unsafe values as strings to ensure that they aren't converted to scientific notation as well as coerce strings-to-numbers when desired.  (NOTE: Here's a whole [thread](https://excel.uservoice.com/forums/304921-excel-for-windows-desktop-application/suggestions/10374741-stop-excel-from-changing-large-numbers-actually?tracking_code=7bef3a59dadf38daa8fe0b44dc849ed4) from 2015 dedicated to the issue that has 1.8k votes on a "started" feature request.

**Comment by cfsimplicity** [comment]
Did you look at [ColdFusion's `datatype` parameter](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-s/spreadsheetaddrow.html) (introduced in ACF11)? This is basically an override you can use when adding single or multiple rows, or columns.

Rather than setting the type per named column (like your UDF), it allows you to specify the datatypes of each column in each row in the case of `spreadsheetAddRows()`. So you could pass an array of custom row specifications equal to the number of rows in the data. I can't imagine that's something you'd want to do with a big dataset, but it does in theory give you completely granular control.

With `spreadsheetAddColumn()` you can also set the type for each row.

From some quick testing, it appears to "fallback" in the way you describe, i.e. if you specify NUMERIC for the value "-" it will ignore it and set it to STRING.

But as I've said before, I'm anticipating it being a _lot_ of work to implement, which is why I haven't tackled it up to now, with the exception of [`setCellValue()`](https://github.com/cfsimplicity/lucee-spreadsheet/wiki/setCellValue), which does have a `type` option.

Incidentally, it seems my `setCellValue()` differs from ACF's in that if you specify a type, it will be applied regardless, whereas ACF's will only apply it if the value matches the type (like the fallback above). In the case of setting a single cell value, I think my approach is correct! If the developer has explicitly asked for the value to be cast as a number, then that's what should happen. But it potentially makes trying to implement the `datatype` option across the board even more complicated.

**Comment by JamoCA** [comment]
I really don't like how Adobe implemented it... the format is different than anything else AND requires using positional instructions.  If you use exports that may change fields or field order, this is a huge mess. (The example code appears to be invalid since line 31 only displays "DATE:" and no column number.)

The first patch that I submitted performed a generic upgrade of any VARCHAR values to a blanket NUMERIC, DATE, TIME and/or BOOLEAN for all columns.  (You could select... it's wasn't an all-or-nothing option.)  This approach may not be entirely safe, in my one use-case where I generating query data for an unknown amount of response-related columns, it made sense.

Alternatively my QuerytoCSV UDF uses the data type from [getmetadata](https://cfdocs.org/getmetadata), but before outputting it checks to see if an override exists (ie, `{"Score"="numeric"}` and whether the value is valid to export as the type.   If it's not valid (ie, a non-numeric value like empty or '`'), it defaults to the fallback column-type behavior.  No harm done and it's name-based rather than relying on a static, non-changing column order (default) or writing extra logic to determine this and pass it for every row (new CF11 datatype attribute).

I need this as this is the only thing that my clients have complained about when I've used this CFC versus using a Windows CSV-to-XLSX EXE that I was using.

**Comment by cfsimplicity** [comment]
I don't like the ACF implementation either: I think it's complex to use and difficult to replicate - I wonder how many people are actually using it (I can't find it mentioned online other than in the docs). Agree that field order changes could mess up the positional instructions, but OTOH not all data sets have column names (what if I pass an array to `addRows()`?).

I'm not really sure though what your preference is? This fix #199 does what your first patch does, i.e. lets the default auto-type detection work for queries, ignoring the column types.

But then you're saying your UDF does something different to address other potential issues, but as I say it can only apply to query data with column names, so it's not a universal solution.

Are you happy for me to release this change and then think about addressing problems that remain as a separate fix? Or is it better to hold off and think this through a bit more before committing to anything?

**Comment by cfsimplicity** [comment]
I do think this needs to be applicable to array data as well as queries and have come up with [an implementation](https://github.com/cfsimplicity/lucee-spreadsheet/issues/200) that does that, while also I hope addressing your concerns. Could you give it a spin on the develop branch? Thanks.

**Comment by JamoCA** [comment]
This works correctly. Thanks.
