### ISSUE TITLE
query limit to 9999 records

### ISSUE THREAD

**Issue by ivanionut** [cfsimplicity/lucee-spreadsheet#211]
Hi @cfsimplicity ,
today i was trying to open an xlsx file with
`qry = spreadsheet.read(src=this.local_path_catalog, headerRow=1, format="query" );`

and I noticed that the query is 9999 records _(my xlsx file contains 10759 lines)_.
I'm wrong somewhere? 🤔

---

my environment:

- openjdk11
- lucee@5.3.8-SNAPSHOT+117
- lucee-spreadsheet 2.12.2

**Comment by cfsimplicity** [comment]
Hi @ivanionut . I'm afraid I can't replicate your issue. I have a large 80,000 row XLSX file I use for testing and reading it into a query results in the correct number of records:
```
spreadsheet = New luceeSpreadsheet.SpreadSheet();
qry = spreadsheet.read( src=ExpandPath( "large.xlsx" ), headerRow=1, format="query");
dump( qry.recordcount );//80,000
```
I used the same version of Lucee/Java as you.

How are you checking the number of query records?

What happens if you read the file as a workbook object, and then check the number of rows?

```
wb = spreadsheet.read( src=this.local_path_catalog );
dump( wb.getRowCount() );
```

**Comment by ivanionut** [comment]
hi @cfsimplicity,
yes, `qry.getRowCount()` or `qry.recordcount` gives me the correct value.

Trying to do the `dump(qry)` breaks my query to 9999 records. At this point I think the problem is Lucee...

Thanks for your help!
