### ISSUE TITLE
spreadsheet.read(format="query") doesn't return column data types when using getMetaData()

### ISSUE THREAD

**Issue by JamoCA** [cfsimplicity/lucee-spreadsheet#224]
I ran into an issue when I replaced Lucee-Spreadsheet with CFSpreadsheet due to the absence of the query data type for each column.

If I use `getMetaData()` on a query returned by CFSpreadsheet, there are three (3) keys for each column: `IsCaseSensitive`, `Name` and `TypeName`.  If I use Lucee-Spreadsheet, only two (2) keys (`IsCaseSensitive` and `Name`) are returned when using `getMetaData()`.

I had a pre-existing UDF that checked TypeName in order to output the values correctly and the lack of this data threw an error. (I've updated my UDF so that it checks for the existence of the key first.)

**Comment by JamoCA** [comment]
I also discovered that without this data, it's difficult to perform a QofQ on the Lucee-Spreadsheet generated query.  The error I was encountering with a simplish `SELECT * FROM query WHERE Column = 1` was a strange `couldn't convert "" to a number` and we initially thought it was due to client-provided data.

**Comment by cfsimplicity** [comment]
Interesting can-of-worms you seem to have opened, James!

Firstly, this is only an issue with ACF.  Run `GetMetaData( queryFromSpreadsheetLibrary )` in Lucee and each column will have all 3 keys.

Why isn't ACF including the `TypeName` key?

It seems to be because when the library is generating the query using `QueryNew()` it is not specifying the column types, i.e. it's just passing an empty string.

Why is the library not specifying the column types when converting from a spreadsheet or CSV to a CFML query?

Because in POI (and CSV) there is no such thing as a "column type". In POI, only cells have types. A column may contain values of different types and it'd be risky to declare that all values in a given column are of the same type. So we don't specify any column types when generating queries from spreadsheets or CSV.

This doesn't trouble Lucee when using `GetMetaData()` because it tries to detect each column type based on its values. From my testing, if they can all be cast to the same type, you'll see that. Otherwise it'll be VARCHAR.

Unfortunately, ACF is not so smart.  You said that `<cfspreadsheet>` returns the `TypeName` key when reading into a query, but in my tests, it's *always* VARCHAR, even if all the values in the spreadsheet column are clearly another type. So not reliable at all.

My initial thought was to mimic that and just specify VARCHAR for each column when creating the query. That worked in terms of forcing ACF to include the `TypeName` key, but it also meant all the values in the query were then treated as strings. This caused some existing tests to fail for functionality which depends on values being a specific type.

I suppose we could try to be smart like Lucee in `GetMetaData()` and detect the column types at creation, but it's one thing to *guess* a type, an another to *impose* types on a whole column, which may be a mixture.

At this point, my view is that this as an unfortunate ACF bug with no obvious workaround.

**Comment by JamoCA** [comment]
This ACF bug hit me hard.  I couldn't perform ACF QofQs on imported Excel data using LuceeSpreadsheet like I could when using CFSpreadsheet.  We are always very specific with column types whenever we dynamically create queries using `queryNew()` or `queryAddColumn()` because we never ever know how QofQs are going to behave.  One numeric or date Excel column I recently imported using LuceeSpreadsheet on ACF had a query `TypeName` of `JAVA_OBJECT`.  I'm not sure how that happened... maybe that's what happens when importing typeless and then manually adding some values to a perceived-typecast column using `Javacast()`.

In the past, I've required some clients to duplicate the header row so that all columns were treated as `VARCHAR` since empty cells or inconsistent data in the first couple of rows resulted in the wrong data type.

To workaround this issue for now, I've written a UDF wrapper to import Excel data that will use an IF rule to use LuceeSpreadsheet with Lucee and CFSpreadSheet with ACF.  (I was hoping to standardize soley on this library.)

**Comment by cfsimplicity** [comment]
@JamoCA I can see this is bit of problem on ACF, so I've come up with what I hope will help you get round it.

I've added a new optional attribute `queryColumnTypes` to the `read()` method (see #225 ). This allows you to either:

a) specify the list of column types you want used when the query is created, e.g.
```
query = spreadsheet.read( src=path, format="query", queryColumnTypes="INTEGER,DATE,VARCHAR" );
```
or:

b) have the library auto-detect the types from the values
```
query = spreadsheet.read( src=path, format="query", queryColumnTypes="auto" );
```
The latter looks at the values in each column. If they are all one type, that will be used. If they are mixed it'll be VARCHAR. Blank cells are ignored. Reliable detection is quite tricky and so only 3 different types are currently supported: VARCHAR, TIMESTAMP and DOUBLE (to cover integers and floats). There is also a bit of a performance overhead with this option, so expect sheets with many columns to take longer to process.

Whichever way you use it, the resulting query will always have column types that will show up in `GetMeta( query )`.

Please test the latest `develop` branch and let me know if that's OK.

**Comment by JamoCA** [comment]
Could you add support for a struct. Usually I'll know which column headers I'm expecting and the format that they should be in, but not the order.

If not added, I'd need to check first column to determine headers and order, then loop through the values to manually generate a list in the same order. I wrote a CSV/Excel UDF that uses similar arguments (list and/or struct support) and the struct is nice because it only applies rules if column names match. Lost order is good too if you are working with a file that may not have a consistent header (or no header).

**Comment by cfsimplicity** [comment]
Could you post your UDF so I can see what you have in mind?

Bear in mind spreadsheets don't always have header rows, in which case a struct wouldn't make any sense.

**Comment by cfsimplicity** [comment]
I guess accepting a struct would require the `headerRow` argument to be present, and throw an error otherwise.

**Comment by JamoCA** [comment]
I tried the development branch and it actually returned dates using `TIMESTAMP`... ACF doesn't even do this... CFSpreadsheet returns dates as `VARCHAR`.

Here's the type of logic that I use for the setup when defining the data types for queryNew().  Anything that isn't explicitly defined is returned as `VARCHAR`.

```
var columnTypeList =[];
if (structKeyExists(arguments.queryColumnTypes, columnName) and listFindNoCase("Integer,BigInt,Double,Decimal,VarChar,Binary,Bit,Time,Date,TimeStamp", arguments.queryColumnTypes[columnName]) ){
	arrayAppend(columnTypeList, arguments.queryColumnTypes[columnName]);
} else {
	arrayAppend(columnTypeList, "VARCHAR");
}
results = queryNew(columnNames, arrayToList(columnTypeList) );
```

**Comment by cfsimplicity** [comment]
OK, I've added a 3rd option which accepts a struct where the key is the column name and the value the type:
```
columnTypes = { "text column": "VARCHAR", dates: "DATE", times: "TIME" };
// you must either specify the headerRow in which these column names appear...
query = spreadsheet.read( src=path, format="query", queryColumnTypes=columnTypes, headerRow=1 );
// ...or supply the columnNames to use
columnNames = "dates,times,text column";
query = spreadsheet.read( src=path, format="query", queryColumnTypes=columnTypes, columnNames=columnNames );
```
The column types are not sanitized because this is programmer input which IMO should trigger feedback in the form of an exception if any are invalid (ACF will do that).

Please test. Thanks.

**Comment by JamoCA** [comment]
Thanks!  It works well with the unit tests that I've written.

While it is a lot slower on ACF, specifying query column types appears to be much faster than using `auto` and only slightly slower than using `null` on both Lucee & CF2021.

**Comment by cfsimplicity** [comment]
Available as [v2.16.0](https://github.com/cfsimplicity/lucee-spreadsheet/releases/tag/v2.16.0)

**Comment by cfsimplicity** [comment]
Setting the default to `varchar` without auto-detection, like `cfspreadsheet`, would also be a potentially breaking change (as I said I had a couple of tests fail when I tried). But the optional hooks are there now for you to address the issues you've had.

**Comment by cfsimplicity** [comment]
@JamoCA I've added another way of using `queryColumnTypes`: if you pass a _single_ type (not a list), that will be applied to _all_ columns in the query, e.g.:
```
query = spreadsheet.read( src=path, format="query", queryColumnTypes="VARCHAR" );
```
This will make it behave like ACF: a bit "dumb" but at least you don't need to know anything in advance about the data, and you avoid the overhead of `auto` detection.

It's on `develop` for now, where also I've added all the same new query control features to `csvToQuery()`.
