### ISSUE TITLE
Enhancement for RBG Colors

### ISSUE THREAD

**Issue by franktudor** [cfsimplicity/lucee-spreadsheet#98]
I really love this tool. I am wondering if there is a way to provide an RBG color override for the default color choices.  I was looking into some of the functions and was unable to find something, maybe there is something there that I couldn't discover, but if not I wanted to raise it as a request not an actual issue.

**So for example when you have a line that looks like this:**

spreadSheet.formatRows( workbook,{bold="true",fontsize="10",color="white",fgcolor="DARK_BLUE",alignment="center",textwrap="true",verticalalignment="vertical_center"},"2,3" );

**We could do something like:** 

spreadSheet.formatRows( workbook,{bold="true",fontsize="10",colorOverride="255,255,255",fgcolorOverride="255,255,255",alignment="center",textwrap="true",verticalalignment="vertical_center"},"2,3" );

**Comment by cfsimplicity** [comment]
Thanks for the suggestion Frank. I've attempted to add support for using RGB triplet values instead of the pre-set palette names whenever specifying the `color` format, and this seems to work fine with the xml spreadsheet format (XSSF). 
```
spreadSheet.formatRows( workbook, { color="181,133,212", fgcolor="0,0,255" },"2,3" );
```
With the older binary format (HSSF) it's a bit more tricky.

With HSSF it seems you can only specify colours already in the workbook object's palette. It is possible to _replace_ those colours, but not add to them (despite the existence of a method purporting to do that). I'd be wary of replacing those defaults though in case they were called upon subsequently, so what I've done is allow the RGB value to be specified but instead of the exact value, the nearest default colour will be used.

So if you want to specify the exact RGB colours, you need to make sure your spreadsheet is an .xlsx not .xls.

Could you please test the latest version in Master (0.9.4-alpha) and confirm it's OK?
